name = "CoveragePackage"
uuid = "51df6587-33c1-4735-92b6-a3f782a0267e"
authors = ["Matěj Račinský <matej.racinsky@avast.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
